### ISSUE TITLE
Using GitHub Release

### ISSUE THREAD

**Issue by mertssmnoglu** [ismailcankaratas/voice-assistant#2]
Using GitHub Release to distribute an .exe file is much better.
This will decrease the size and clone time.

You can create a new release and upload your latest .exe binary file. There is no need for `dist` directory

![resim](https://user-images.githubusercontent.com/61623638/224553753-993ed82a-50ab-4bd5-95e2-cb4a155456e7.png)

### Link

Example link: https://github.com/mertssmnoglu/voice-assistant/releases/download/v1.0/aiVoiceAssistant.exe

**Comment by ismailcankaratas** [comment]
Thank you. I made an update
